# Form implementation generated from reading ui file 'Admin_Menu.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.



from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(596, 576)
        font = QtGui.QFont()
        font.setPointSize(10)
        MainWindow.setFont(font)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("QWidget {\n"
"    background-color: #f0f8ff;\n"
"}\n"
"\n"
"QPushButton {\n"
"    background-color: #4CAF50;\n"
"    color: white;\n"
"    border-radius: 8px;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #45a049;\n"
"}\n"
"\n"
"QLineEdit {\n"
"    border: 2px solid #ccc;\n"
"    border-radius: 4px;\n"
"    padding: 4px;\n"
"    background-color: #ffffff;\n"
"}\n"
"")
        def open_preference_admin_menu(self):
                self.window = QtWidgets.QMainWindow()
                self.ui = Ui_PreferenceAdminMenu()
                self.ui.setupUi(self.window)
                self.window.show()
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_7 = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame_7.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_7.setObjectName("frame_7")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_7)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(141, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.label = QtWidgets.QLabel(parent=self.frame_7)
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("Icons/png/rsz_rsz_logo_vit-7-3-2.png"))
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.label_3 = QtWidgets.QLabel(parent=self.frame_7)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout.addWidget(self.frame_7)
        self.frame_5 = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame_5.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btnMentorTanimlanan_8 = QtWidgets.QPushButton(parent=self.frame_5)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.btnMentorTanimlanan_8.setFont(font)
        self.btnMentorTanimlanan_8.setStyleSheet("QPushButton {\n"
"    background-color: #55aaff;\n"
"    color: white;\n"
"    border-radius: 8px;\n"
"    padding: 8px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #8263c6;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #594097;\n"
"}\n"
"")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Icons/png/IMG-20250529-WA0011.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btnMentorTanimlanan_8.setIcon(icon)
        self.btnMentorTanimlanan_8.setObjectName("btnMentorTanimlanan_8")
        self.horizontalLayout_2.addWidget(self.btnMentorTanimlanan_8)
        self.btnMentorTanimlanan_11 = QtWidgets.QPushButton(parent=self.frame_5)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.btnMentorTanimlanan_11.setFont(font)
        self.btnMentorTanimlanan_11.setStyleSheet("QPushButton {\n"
"    background-color: #55aaff;\n"
"    color: white;\n"
"    border-radius: 8px;\n"
"    padding: 8px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #8263c6;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #594097;\n"
"}\n"
"")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("Icons/png/IMG-20250529-WA0016.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btnMentorTanimlanan_11.setIcon(icon1)
        self.btnMentorTanimlanan_11.setObjectName("btnMentorTanimlanan_11")
        self.horizontalLayout_2.addWidget(self.btnMentorTanimlanan_11)
        self.btnMentorTanimlanan_14 = QtWidgets.QPushButton(parent=self.frame_5)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.btnMentorTanimlanan_14.setFont(font)
        self.btnMentorTanimlanan_14.setStyleSheet("QPushButton {\n"
"    background-color: #55aaff;\n"
"    color: white;\n"
"    border-radius: 8px;\n"
"    padding: 8px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #8263c6;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #594097;\n"
"}\n"
"")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("Icons/png/IMG-20250529-WA0007.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btnMentorTanimlanan_14.setIcon(icon2)
        self.btnMentorTanimlanan_14.setObjectName("btnMentorTanimlanan_14")
        self.horizontalLayout_2.addWidget(self.btnMentorTanimlanan_14)
        self.btnMentorTanimlanan_15 = QtWidgets.QPushButton(parent=self.frame_5)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.btnMentorTanimlanan_15.setFont(font)
        self.btnMentorTanimlanan_15.setStyleSheet("QPushButton {\n"
"    background-color: #55aaff;\n"
"    color: white;\n"
"    border-radius: 8px;\n"
"    padding: 8px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #8263c6;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #594097;\n"
"}\n"
"")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("Icons/png/exit-icon.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btnMentorTanimlanan_15.setIcon(icon3)
        self.btnMentorTanimlanan_15.setObjectName("btnMentorTanimlanan_15")
        self.horizontalLayout_2.addWidget(self.btnMentorTanimlanan_15)
        self.verticalLayout.addWidget(self.frame_5)
        self.tblSonuclar = QtWidgets.QTableWidget(parent=self.centralwidget)
        self.tblSonuclar.setObjectName("tblSonuclar")
        self.tblSonuclar.setColumnCount(4)
        self.tblSonuclar.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tblSonuclar.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblSonuclar.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblSonuclar.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblSonuclar.setHorizontalHeaderItem(3, item)
        self.verticalLayout.addWidget(self.tblSonuclar)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_3.setText(_translate("MainWindow", "C R M - ADMIN MENU"))
        self.btnMentorTanimlanan_8.setText(_translate("MainWindow", "Activity Control"))
        self.btnMentorTanimlanan_11.setText(_translate("MainWindow", "Send Mail"))
        self.btnMentorTanimlanan_14.setText(_translate("MainWindow", "Preference Admin Menu"))
        self.btnMentorTanimlanan_15.setText(_translate("MainWindow", "Exit"))
        item = self.tblSonuclar.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Activity Name"))
        item = self.tblSonuclar.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Start Time"))
        item = self.tblSonuclar.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Participant Mail"))
        item = self.tblSonuclar.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Organiser Mail"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())