# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(513, 572)
        MainWindow.setStyleSheet("QWidget {\n"
"    background-color: #f0f8ff;\n"
"}\n"
"\n"
"QPushButton {\n"
"    background-color: #4CAF50;\n"
"    color: white;\n"
"    border-radius: 8px;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #45a049;\n"
"}\n"
"\n"
"QLineEdit {\n"
"    border: 2px solid #ccc;\n"
"    border-radius: 4px;\n"
"    padding: 4px;\n"
"    background-color: #ffffff;\n"
"}\n"
"")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_13 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_13.setText("")
        self.label_13.setPixmap(QtGui.QPixmap("Icons/png/rsz_logo_vit-7-3-1.png"))
        self.label_13.setObjectName("label_13")
        self.verticalLayout_2.addWidget(self.label_13, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.frame_3 = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame_3.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(155, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.label_9 = QtWidgets.QLabel(parent=self.frame_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_2.addWidget(self.label_9)
        spacerItem1 = QtWidgets.QSpacerItem(155, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.verticalLayout_2.addWidget(self.frame_3)
        self.frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.groupBox_10 = QtWidgets.QGroupBox(parent=self.frame)
        self.groupBox_10.setTitle("")
        self.groupBox_10.setObjectName("groupBox_10")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox_10)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox_11 = QtWidgets.QGroupBox(parent=self.groupBox_10)
        self.groupBox_11.setTitle("")
        self.groupBox_11.setObjectName("groupBox_11")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.groupBox_11)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_10 = QtWidgets.QLabel(parent=self.groupBox_11)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_4.addWidget(self.label_10)
        self.leUsername_8 = QtWidgets.QLineEdit(parent=self.groupBox_11)
        self.leUsername_8.setMinimumSize(QtCore.QSize(150, 0))
        self.leUsername_8.setMaximumSize(QtCore.QSize(150, 16777215))
        self.leUsername_8.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.leUsername_8.setObjectName("leUsername_8")
        self.horizontalLayout_4.addWidget(self.leUsername_8)
        spacerItem2 = QtWidgets.QSpacerItem(118, 15, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.verticalLayout.addWidget(self.groupBox_11)
        self.groupBox_12 = QtWidgets.QGroupBox(parent=self.groupBox_10)
        self.groupBox_12.setTitle("")
        self.groupBox_12.setObjectName("groupBox_12")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.groupBox_12)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_11 = QtWidgets.QLabel(parent=self.groupBox_12)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_3.addWidget(self.label_11)
        self.leUsername_9 = QtWidgets.QLineEdit(parent=self.groupBox_12)
        self.leUsername_9.setMinimumSize(QtCore.QSize(150, 0))
        self.leUsername_9.setMaximumSize(QtCore.QSize(150, 16777215))
        self.leUsername_9.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.leUsername_9.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.leUsername_9.setObjectName("leUsername_9")
        self.horizontalLayout_3.addWidget(self.leUsername_9)
        self.checkBox = QtWidgets.QCheckBox(parent=self.groupBox_12)
        self.checkBox.setObjectName("checkBox")
        self.horizontalLayout_3.addWidget(self.checkBox)
        spacerItem3 = QtWidgets.QSpacerItem(119, 15, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.verticalLayout.addWidget(self.groupBox_12)
        self.verticalLayout_9.addWidget(self.groupBox_10)
        self.groupBox_13 = QtWidgets.QGroupBox(parent=self.frame)
        self.groupBox_13.setTitle("")
        self.groupBox_13.setObjectName("groupBox_13")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.groupBox_13)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.btnLogin_3 = QtWidgets.QPushButton(parent=self.groupBox_13)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.btnLogin_3.setFont(font)
        self.btnLogin_3.setStyleSheet("QPushButton {\n"
"    background-color: #55aaff;\n"
"    color: white;\n"
"    border-radius: 8px;\n"
"    padding: 8px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #8263c6;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #594097;\n"
"}\n"
"")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Icons/png/IMG-20250529-WA0022.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btnLogin_3.setIcon(icon)
        self.btnLogin_3.setIconSize(QtCore.QSize(24, 24))
        self.btnLogin_3.setObjectName("btnLogin_3")
        self.verticalLayout_8.addWidget(self.btnLogin_3)
        self.pushButton_6 = QtWidgets.QPushButton(parent=self.groupBox_13)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setStyleSheet("QPushButton {\n"
"    background-color: #55aaff;\n"
"    color: white;\n"
"    border-radius: 8px;\n"
"    padding: 8px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #8263c6;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #594097;\n"
"}\n"
"")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("Icons/png/exit-icon.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_6.setIcon(icon1)
        self.pushButton_6.setIconSize(QtCore.QSize(24, 24))
        self.pushButton_6.setObjectName("pushButton_6")
        self.verticalLayout_8.addWidget(self.pushButton_6)
        self.lblMessage_3 = QtWidgets.QLabel(parent=self.groupBox_13)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lblMessage_3.setFont(font)
        self.lblMessage_3.setObjectName("lblMessage_3")
        self.verticalLayout_8.addWidget(self.lblMessage_3)
        self.verticalLayout_9.addWidget(self.groupBox_13)
        self.groupBox_13.raise_()
        self.groupBox_10.raise_()
        self.verticalLayout_2.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem4 = QtWidgets.QSpacerItem(474, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem4)
        self.verticalLayout_2.addWidget(self.frame_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action1_Bsamak = QtGui.QAction(parent=MainWindow)
        self.action1_Bsamak.setObjectName("action1_Bsamak")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_9.setText(_translate("MainWindow", " C R M -  PROJECT"))
        self.label_10.setText(_translate("MainWindow", "User Name"))
        self.label_11.setText(_translate("MainWindow", "Password  "))
        self.checkBox.setText(_translate("MainWindow", "Show"))
        self.btnLogin_3.setText(_translate("MainWindow", "Login"))
        self.pushButton_6.setText(_translate("MainWindow", "Exit"))
        self.lblMessage_3.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Login Message</p></body></html>"))
        self.action1_Bsamak.setText(_translate("MainWindow", "1. Bsamak"))
